<body class='claro'>
<fieldset><legend><?php echo $this->translate("Scheme Setup");?></legend>
<Form dojoType="dijit.form.Form" id="myForm" action="" method="post" name="myForm">
<script type="dojo/method" event="onSubmit" >
               if (this.validate()) {
                   return true;
                 } else {
                   return false;
 	           }
</script>
<table class="table" width="40%">
	<tr>
		<th colspan="2"><?php echo $this->translate("New Scheme Setup");?></th>
	</tr>
		<tr>
		<td><?php echo $this->translate("ID PD");?><span class="reqMark">*</span></td>
		<td><?php echo $this->lobjSchemesetupForm->id_pd;?></td>
		</tr>
	<tr>
		<td><?php echo $this->translate("Nama");?><span class="reqMark">*</span></td>
		<td><?php echo $this->lobjSchemesetupForm->nm_pd;?></td>
		</tr>
		<tr>
		<td><?php echo $this->translate("Jantina");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->jk;?></td>
		</tr>
	<tr>
		<td><?php echo $this->translate("Tempat Lahir");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->tmpt_lahir;?></td>
  </tr>
   <tr>
	<td><?php echo $this->translate("Tgl Lahir");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->tgl_lahir;?></td>
  </tr>
   <tr>
	<td><?php echo $this->translate("ID Wilayah");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->id_wil;?></td>
  </tr>
   <tr>
	<td><?php echo $this->translate("a_terima_kps");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->a_terima_kps;?></td>
  </tr>
   <tr>
	<td><?php echo $this->translate("id agama");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->id_agama;?></td>
  </tr>
  <tr>
	<td><?php echo $this->translate("id_kebutuhan_khusus_ayah");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->id_kebutuhan_khusus_ayah;?></td>
  </tr>
  <tr>
	<td><?php echo $this->translate("nm_ibu_kandung");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->nm_ibu_kandung;?></td>
  </tr>
    <tr>
	<td><?php echo $this->translate("id_kebutuhan_khusus_ibu");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->id_kebutuhan_khusus_ibu;?></td>
  </tr>
</table>
<table class="table" width="40%">
      <tr>
	    <td align="right"><?php echo $this->lobjSchemesetupForm->Save;?>
		<?php echo $this->lobjSchemesetupForm->Back;?></td>
	</tr>
</table>
</Form>
</body>
