<body class='claro'>
<fieldset><legend><?php echo $this->translate("Update Student Profile");?></legend>
<Form dojoType="dijit.form.Form" id="myForm" action="" method="post" name="myForm">
<script type="dojo/method" event="onSubmit" >
               if (this.validate()) {
                   return true;
                 } else {
                   return false;
 	           }

</script>
<table class="table" width="40%">
	<tr>
		<th colspan="2"><?php echo $this->translate("Edit Student Profile");?></th>
	</tr>
		<tr>
		<td><?php echo $this->translate("ID");?><span class="reqMark">*</span></td>
		<td><?php echo $this->lobjSchemesetupForm->id;?></td>
		</tr>
	<tr>
		<td><?php echo $this->translate("Nama Awal");?><span class="reqMark"></span></td>
		<td><?php echo $this->lobjSchemesetupForm->appl_fname;?></td>
		</tr>
		<tr>
		<tr>
		<td><?php echo $this->translate("Nama Tengah");?><span class="reqMark"></span></td>
		<td><?php echo $this->lobjSchemesetupForm->appl_mname;?></td>
		</tr>
		<tr>
		<td><?php echo $this->translate("Nama Akhir");?><span class="reqMark"></span></td>
		<td><?php echo $this->lobjSchemesetupForm->appl_lname;?></td>
		</tr>
		<tr>
		<td><?php echo $this->translate("Jantina");?><span class="reqMark"></span></td>
		<td><?php echo $this->lobjSchemesetupForm->appl_gender;?></td>
		</tr>
		<tr>
		<td><?php echo $this->translate("Tanggal Lahir");?><span class="reqMark"></span></td>
		<td><?php echo $this->lobjSchemesetupForm->appl_dob;?></td>
		</tr>
		<tr>
			<tr>
		<td><?php echo $this->translate("Tempat Lahir");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->appl_birth_place;?></td>
  </tr>
		<td><?php echo $this->translate("Agama");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->appl_religion;?></td>
		</tr>

   <tr>
	<td><?php echo $this->translate("Warganegara");?></td></td>
		<td><?php echo $this->lobjSchemesetupForm->appl_nationality;?></td>
  </tr>
  
   <tr>
   
   


</table>
<table class="table" width="40%">
      <tr>
	    <td align="right"><?php echo $this->lobjSchemesetupForm->Save;?>
		<?php echo $this->lobjSchemesetupForm->Back;?></td>
	</tr>
</table>
</Form>
</body>
